spring:
  application:
    name: Project-Manajemen-Risiko-Kinerja-Fraud
  datasource:
    username: majapahit
    password: Madiun@123
    url: jdbc:postgresql://localhost:5432/manajemen_risiko_fraud
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: jdbc:postgresql://localhost:5432/manajemen_risiko_fraud
  security:
    user:
      name: admin
      password: admin123
  data:
    redis:
      host: localhost
      port: 6379
  keycloak:
    token-url: https://auth.kertaskerja.cc/realms/KabMadiun/protocol/openid-connect/token
    client-id: edge-service
    client-secret: C7KhyeyGrxGEWFYeQsWzxp12Ty25gI3o
    username: admin_test
    password: 123456
external:
  rekin:
    base-url: https://api-ekak.zeabur.app
logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace
      springdoc: DEBUG
      springframework:
        web: DEBUG
      flywaydb: INFO
    io:
      swagger: DEBUG
    cc:
      kertaskerja:
        manrisk_fraud: INFO
        aop: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    disable-swagger-default-url: true
  override-with-generic-response: false
  show-actuator: false
